#!/bin/bash
chmod +x scripts/rad-1.sh
chmod +x scripts/rad-2.sh
chmod +x scripts/rad-3.sh
chmod +x scripts/rad-4.sh
chmod +x scripts/rad-5.sh
chmod +x scripts/rad-6.sh
chmod +x scripts/rad-7.sh
chmod +x scripts/rad-8.sh
chmod +x scripts/rad-9.sh
chmod +x scripts/rad-10.sh
chmod +x scripts/rad-11.sh
chmod +x scripts/rad-12.sh
chmod +x scripts/rad-13.sh
chmod +x scripts/rad-14.sh
chmod +x scripts/rad-15.sh
chmod +x scripts/rad-16.sh
chmod +x scripts/rad-17.sh
chmod +x scripts/rad-18.sh
chmod +x scripts/rad-19.sh
chmod +x scripts/rad-20.sh
chmod +x scripts/rad-21.sh
chmod +x scripts/rad-22.sh
chmod +x scripts/rad-23.sh
chmod +x scripts/rad-24.sh
chmod +x scripts/rad-25.sh
chmod +x scripts/rad-26.sh
chmod +x scripts/rad-27.sh
chmod +x scripts/rad-28.sh
chmod +x scripts/rad-29.sh
chmod +x scripts/rad-30.sh
chmod +x scripts/rad-31.sh
chmod +x scripts/rad-32.sh
chmod +x scripts/rad-33.sh
chmod +x scripts/rad-34.sh
chmod +x scripts/rad-35.sh
chmod +x scripts/rad-36.sh
chmod +x scripts/rad-37.sh
chmod +x scripts/rad-38.sh
chmod +x scripts/rad-39.sh
chmod +x scripts/rad-40.sh
chmod +x scripts/rad-41.sh
chmod +x scripts/rad-42.sh
chmod +x scripts/rad-43.sh
chmod +x scripts/rad-44.sh
chmod +x scripts/rad-45.sh
chmod +x scripts/rad-46.sh
chmod +x scripts/rad-47.sh
chmod +x scripts/rad-48.sh
chmod +x scripts/rad-49.sh
chmod +x scripts/rad-50.sh
chmod +x uninstall.sh